// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Build(arg1) {
  return window['go']['main']['App']['Build'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function ScanProject(arg1) {
  return window['go']['main']['App']['ScanProject'](arg1);
}
