// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Build(arg1:main.BuildParams):Promise<main.BuildResult>;

export function OpenDirectory():Promise<string>;

export function ScanProject(arg1:string):Promise<main.ScanResult>;
